# Generated by Django 4.0 on 2023-08-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transporteurs',
            options={'ordering': ['name', 'firstname'], 'verbose_name': 'Transporteur', 'verbose_name_plural': 'Transporteurs'},
        ),
        migrations.AlterModelOptions(
            name='transports',
            options={},
        ),
        migrations.AlterModelOptions(
            name='voyages',
            options={},
        ),
        migrations.RenameField(
            model_name='compagnie',
            old_name='nom_E',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='transporteurs',
            old_name='nom',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='transporteurs',
            old_name='prenom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='voyageurs',
            old_name='nom_V',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='voyageurs',
            old_name='prenom_V',
            new_name='name',
        ),
    ]
