# Generated by Django 4.0 on 2023-08-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_alter_transporteurs_options_alter_transports_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transports',
            options={'verbose_name': 'Transport', 'verbose_name_plural': 'Transports'},
        ),
        migrations.AlterModelOptions(
            name='voyages',
            options={'verbose_name': 'Voyage', 'verbose_name_plural': 'Voyages'},
        ),
    ]
