# Generated by Django 5.0.14 on 2025-06-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_voyageurs_ticket_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyageurs',
            name='password_reset_required',
            field=models.BooleanField(default=True),
        ),
    ]
