# Generated by Django 5.0.14 on 2025-06-15 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_voyageurs_password_reset_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.voyages')),
                ('voyageur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.voyageurs')),
            ],
        ),
    ]
