# Generated by Django 5.0.14 on 2025-06-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('voyageur', 'Voyageur'), ('chauffeur', 'Chauffeur')], default='voyageur', max_length=20),
        ),
    ]
