# Generated by Django 5.0.14 on 2025-06-23 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_transports_bagages_disponibles_transports_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transports',
            name='voyages',
        ),
        migrations.AddField(
            model_name='voyages',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.transports'),
        ),
    ]
