# Generated by Django 5.0.14 on 2025-07-27 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0009_historiqueimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteurs',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transporteurs',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='transporteurs',
            name='permis',
            field=models.CharField(choices=[('A', 'Permis A'), ('B', 'Permis B'), ('C', 'Permis C'), ('D', 'Permis D'), ('BE', 'Permis BE'), ('C1E', 'Permis C1E')], default='B', max_length=5),
        ),
    ]
