# Generated by Django 5.0.14 on 2025-06-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='transports',
            name='bagages_disponibles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transports',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transports',
            name='places_disponibles',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
