# Generated by Django 5.0.14 on 2025-06-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_remove_transports_voyages_voyages_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='transports',
            name='transporteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.transporteurs'),
        ),
    ]
